export const PLAY_SONG = 'PLAY_SONG';

export const PAUSE_SONG = 'PAUSE_SONG';

export const SELECT_SONG = 'SELECT_SONG';

export const CHANGE_PLAYBACK_TIME = 'CHANGE_PLAYBACK_TIME';

export const PLAY_NEXT_SONG = 'PLAY_NEXT_SONG';

export const PLAY_PREVIOUS_SONG = 'PLAY_PREVIOUS_SONG';

export const CHANGE_VOLUME = 'CHANGE_VOLUME';