export default [
    'Bring music to life.',
    'Dance to the rhythm of your heart.',
    'Face the music.',
    'Flute: We give a hoot.',
    'Gone Chopin … Bach in five.',
    'Got Mozart?',
    'If you can’t teach me to fly than teach me music..',
    'Let music flow in your heart and enrich your soul.',
    'Let the Music Speak!',
    'Life is a song, love is the music.',
    'Like music to my ears.',
    'Love is my weapon, music is my religion, peace is in my soul.',
    'Modern music is as dangerous as cocaine.',
    'Music = Life.',
    'Music brings harmony to the world.',
    'Music chose me, not the other way around.',
    'Music is an outburst of the soul.',
    'Music is my life.',
    'Music is My Time Machine.',
    'Music is only love looking for words.',
    'music is poetry, poetry are lyrics to the soul.',
    'Music is the art of thinking with sounds.',
    'Music is the shorthand of emotion.',
    'Music is what feelings sound like.',
    'Music is what I am. Everything else is what I do.',
    'Music makes the world go round.',
    'Music only makes me stronger.',
    'Music speaks to the heart in ways words cannot express.',
    'Music, the mosaic of the air.',
    'Music: My Anti-depressant.',
    'Rock Off and Rave on.',
    'The sweetest music this side of heaven.',
    'Trumpet: Classy Brassy Sassy!',
    'Tuba: Play with the Big Boys.',
    'Walk softly and carry a big trombone.',
    'We hold our notes longer, better, and higher.',
    'We put the mental in instrumental and the cool in musicool.',
    'When words fail, music speaks.',
    'Where clarinets go, treble follows!',
    'Where words fail, music speaks.',
    'Without music, life would not be fair.'
]